### ISSUE TITLE
error at start

### ISSUE THREAD

**Issue by Owned67** [LesFerch/ClearDefenderHistory#1] opened 2023-12-06 18:28 UTC
`Set-ScheduledTask : Le mappage entre les noms de compte et les ID de sécurité n’a pas été effectué.
(13,8):UserId:
Au caractère Ligne:27 : 1
+ Set-ScheduledTask -TaskPath $SchedulerPath -TaskName $TaskName -Princ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Set-ScheduledTask],
   CimException
    + FullyQualifiedErrorId : HRESULT 0x80070534,Set-ScheduledTask

`

Executed with admin privileges...

**Comment by LesFerch** [comment] 2023-12-06 18:53
I did some research and testing. The problem has nothing to do with language. The issue is related to the user profile. How are you logging into your computer? Local account? Microsoft account? Active Directory account? Is this a personal computer or company owned (i.e. IT department controlled)?

**Comment by Owned67** [comment] 2023-12-07 10:03
Local account and personal computer

**Comment by LesFerch** [comment] 2023-12-07 14:36
Glad to hear the other program worked!

If you wish to investigate the error further...

The error message indicates an issue with an account and how it's name is mapped to its SID. There are three accounts involved. Your local account, the Administrator account, and TrustedInstaller. Since the error occurs at line 27, it appears to be a problem with the Administrator account. If Administrator is currently disabled, try enabling it. If it's already enabled, try disabling and enabling and then test logging in with that account. Note that the script does not require Administrator to be enabled. This is just a troubleshooting step.

[Enable Administrator in Windows 10](https://www.tenforums.com/tutorials/2969-enable-disable-elevated-administrator-account-windows-10-a.html)
[Enable Administrator in Windows 11](https://www.elevenforum.com/t/enable-or-disable-built-in-administrator-account-in-windows-11.709/)

**Comment by Owned67** [comment] 2023-12-08 14:28
Administrator doesn't exist sorry...
My local account are Administrator ^^

**Comment by LesFerch** [comment] 2023-12-09 01:51
I just updated `ClearDefenderHistory.bat`.

It now finds the current Administrator account's name, instead of assuming that it's 'administrator`.

I successfully tested it with several different names. including `administrator^^`.

**Comment by Owned67** [comment] 2023-12-09 08:22
Thanks will try when defender have a history ^^

In french, it's Adminnistrateur ^^

**Comment by LesFerch** [comment] 2023-12-09 16:28
That makes sense. The `^^` that appears in your message threw me off. Anyhow, the updated script definitely works with `Adminnistrateur`, or any other name, so I'll close this one as completed.

**Closed by LesFerch** 2023-12-09 16:28 UTC

**Comment by Owned67** [comment] 2023-12-10 07:42
be carefull with other software you've gave, after used it, history protection stay empty so cannot test your change...

**Comment by LesFerch** [comment] 2023-12-10 08:02
Thanks for letting me know. I asked that moderator for the source code, but no response yet.
